version: '3.8'
services:
  whatsapp-sender:
    build: .
    environment:
      - DISPLAY=:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .:/app
    working_dir: /app
    network_mode: host
    stdin_open: true
    tty: true
    command: bash
